name: Build and Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx update-browserslist-db@latest
        npm run publish

    - name: Adding Known Hosts
      run: |
        mkdir ~/.ssh/
        ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: unnecessary

    - name: Deploy with rsync
      run: rsync -avz ./docs/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/dh_grzdvn/layout-experiments.rivendellweb.net/

